name: Build Web Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install web dependencies
        run: npm install
        working-directory: ./web

      - name: Build web application
        run: npm run build
        working-directory: ./web

      - name: Build success
        run: echo "✅ Web application built successfully"
